<a href="https://colab.research.google.com/github/Stephen-sanchez1/datasci_1_loading/blob/main/HHA_507_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Loading Packages

In [1]:
import pandas as pd
import seaborn as sns
import plotly as plt

### Loading CSV Files

##### CSV file #1

##### **Description of CSV file:** Mass shooting incidents in the United States in 2023.


| Columns |  |
|---|---|
| Incident ID |  |
| Incident date | |
| State | |
| City or county |  |
| Address |  |
| Victims killed |  |
| Victims injured |  |
| Suspects killed |  |
| Suspects injured |  |
| Suspects arrested |  |

In [18]:
#  CSV file #1
# Loading CSV file #1
dataset1 = pd.read_csv('/Mass_shootings_2023.csv')
dataset1.head(10)

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
0,2699229,"September 5, 2023",Illinois,Chicago,4718 W Gladys Ave,0,4,0,0,0,NaN
1,2698496,"September 4, 2023",Alabama,Birmingham,930 5th Ave N,2,3,0,0,0,NaN
2,2698171,"September 3, 2023",Georgia,Atlanta,3516 Adkins Rd NW,0,5,1,0,0,NaN
3,2698786,"September 3, 2023",North Carolina,High Point,2900 block of Creekview Ct,1,3,0,0,0,NaN
4,2698107,"September 3, 2023",Texas,Galveston,4002 Mendocino Dr,2,2,0,0,0,NaN
5,2698160,"September 3, 2023",Illinois,Freeport,300 block of E Pleasant St,1,3,0,0,0,NaN
6,2697278,"September 2, 2023",Massachusetts,Lynn,189 Essex St,2,5,0,0,0,NaN
7,2695977,"August 30, 2023",Texas,Houston,2800 block of Chimney Rock Rd,0,4,0,0,0,NaN
8,2695354,"August 30, 2023",Illinois,Peoria,2217 W Marquette Ave,0,5,0,0,0,NaN
9,2694245,"August 29, 2023",Texas,Texarkana,300 block of Waterman St,0,4,0,0,0,NaN

##### CSV file #2

##### **Description of CSV file:** Unintentional shooting incidents in the United States in 2023.


| Columns |  |
|---|---|
| Incident ID |  |
| Incident date | |
| State | |
| City or county |  |
| Address |  |
| Victims killed |  |
| Victims injured |  |
| Suspects killed |  |
| Suspects injured |  |
| Suspects arrested |  |

In [19]:
#  CSV file #2
# Loading CSV file #2
dataset2 = pd.read_csv('/Unintentional_shootings.csv')
dataset2.head(10)

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
0,2698867,"September 4, 2023",New York,Brooklyn,Eastern Pkwy and Franklin Ave,0,0,0,1,1,NaN
1,2699049,"September 4, 2023",Florida,Casselberry,30 block of Jackson Ct,0,2,0,0,1,NaN
2,2698782,"September 3, 2023",North Carolina,Madison,614 Burton St,1,0,0,0,0,NaN
3,2698050,"September 2, 2023",Arizona,Glendale,83rd Ave and Dreyfus Dr,0,2,0,0,0,NaN
4,2697322,"September 2, 2023",Illinois,Chicago,1800 block of S Blue Island Ave,0,1,0,0,0,NaN
5,2696737,"September 1, 2023",Minnesota,Crosslake,30000 block of Aspen Way,0,1,0,0,0,NaN
6,2696519,"September 1, 2023",Florida,Tallahassee,522 Silver Slipper Ln,1,0,0,0,0,NaN
7,2697720,"September 1, 2023",Louisiana,Shreveport,3000 block of Woodford St,0,1,0,0,0,NaN
8,2696701,"August 31, 2023",Wisconsin,Milwaukee,N 13th St and W Atkinson Ave,0,1,0,0,0,NaN
9,2696508,"August 31, 2023",North Carolina,Statesville,100 block of Fort Dobbs Rd,1,0,0,0,0,NaN

### Loading JSON Files

##### XLSL file #1

##### **Description of JSON file:**


| Columns |  |
|---|---|
|  |  |
|  | |
|  | |
|  |  |
|  |  |
|  |  |
|  |  |
|  |  |
|  |  |
|  |  |

In [26]:
#  JSON file #1
# Loading JSON file #1
dataset3 = pd.read_json(')
dataset3.head(10)

SyntaxError: ignored